Working version for gitlab integration
stuvusIT/mattermost-gitlab-integration pull request #1
Opened 2018-05-04 09:29 UTC by Scriptkiddi

2018-05-04 18:26 UTC, ghost submitted a review, later dismissed
no

2018-05-06 10:36 UTC, SlothOfAnarchy requested changes

2018-05-06 10:36 UTC, SlothOfAnarchy commented on meta/main.yml
> +        - yakkety
yakkety and zesty are not supported anymore, but bionic should be

2018-05-06 10:36 UTC, SlothOfAnarchy commented on README.md
> +| `mattermost_gitlab_integration_username`       | ` `                                      | Username to post under in Mattermost
If there is no default, leave the column empty or use a cross emoji

2018-05-06 10:36 UTC, SlothOfAnarchy commented on README.md
> +[push](http://doc.gitlab.com/ee/web_hooks/web_hooks.html#comment-events)                | :heavy_multiplication_x: | `push`          |
links to comment section instead of push

2018-05-07 14:58 UTC, Scriptkiddi commented
@SlothOfAnarchy pls rerveiw

2018-05-08 01:04 UTC, SlothOfAnarchy approved these changes

2018-05-17 10:46 UTC, merged